import localFont from "next/font/local";
import "./globals.css";
import styles from "./page.module.css";
import 'bootstrap/dist/css/bootstrap.min.css'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Todo App</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.page}>
          <main className={styles.main}>
            {children}
          </main>
          <footer className={styles.footer}>
          </footer>
        </div>
      </body>
    </html>
  );
}
